# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LatLongCalcDialog
                                 A QGIS plugin
 Permite realizar una conversion entre latitud y longitud entre grados decimales y GMS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-03
        git sha              : $Format:%H$
        copyright            : (C) 2021 by hector sosa
        email                : hososa@unah.hn
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'latlongcalc_dialog_base.ui'))


class LatLongCalcDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(LatLongCalcDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        #Conector con las variables de latitud
        self.Spb_Lat_G.valueChanged.connect(self.latDMStoDD)
        self.Spb_Lat_M.valueChanged.connect(self.latDMStoDD)
        self.SpdD_Lat_S.valueChanged.connect(self.latDMStoDD)
        self.Cb_Lat_H.currentTextChanged.connect(self.latDMStoDD)
        
        #Conector con las variables de longitud
        self.Spb_Long_G.valueChanged.connect(self.longDMStoDD)
        self.Spb_Long_M.valueChanged.connect(self.longDMStoDD)
        self.SpdD_Long_S.valueChanged.connect(self.longDMStoDD)
        self.Cb_Long_H.currentTextChanged.connect(self.longDMStoDD)
        
        #conector de grados dedimales a DMS para la latitud
        self.SpdD_Lat_GD.editingFinished.connect(self.latDDtoDMS)
        
        #conector de grados dedimales a DMS para la latitud
        self.SpdD_Long_GD.editingFinished.connect(self.longDDtoDMS)
        
        #conector de UTM
        self.SpdD_UTM_Y.editingFinished.connect(self.to_LatLon)
        self.SpdD_UTM_X.editingFinished.connect(self.to_LatLon)
        self.Spd_UTM.editingFinished.connect(self.to_LatLon)
        self.Cb_UTM.currentTextChanged.connect(self.to_LatLon)
        
        self.Spb_MC.editingFinished.connect(self.to_LatLon)
        
        #conector de 
        self.SpdD_Lat_GD.editingFinished.connect(self.to_UTM)
        self.SpdD_Long_GD.editingFinished.connect(self.to_UTM)    
       
        self.Spd_UTM.editingFinished.connect(self.to_UTM)
        
        self.SpdD_UTM_Y.editingFinished.connect(self.to_UTM)
        self.SpdD_UTM_X.editingFinished.connect(self.to_UTM)
        self.Spb_MC.editingFinished.connect(self.to_UTM)
     
    def latDMStoDD(self):
        iDeg = self.Spb_Lat_G.value()
        iMin = self.Spb_Lat_M.value()
        iSeg = self.SpdD_Lat_S.value()
        sHem = self.Cb_Lat_H.currentText()
        
        dDD = float(iDeg) + iMin/60 + iSeg/3600
        
        if sHem == "S":
            dDD = dDD * -1
        
        self.SpdD_Lat_GD.setValue(dDD)
             
    def longDMStoDD(self):
       iDeg = self.Spb_Long_G.value()
       iMin = self.Spb_Long_M.value()
       iSeg = self.SpdD_Long_S.value()
       sHem = self.Cb_Long_H.currentText()
       
       dDD = float(iDeg) + iMin/60 + iSeg/3600
       
       if sHem == "W":
           dDD = dDD * -1
       
       self.SpdD_Long_GD.setValue(dDD)   

    def latDDtoDMS(self):
        dDD = self.SpdD_Lat_GD.value()
        
        iDeg = int(dDD)
        dMin = (dDD - iDeg) * 60
        iMin = int(dMin)
        dSeg = (dMin - iMin) * 60
        
        self.Spb_Lat_G.setValue(abs(iDeg))
        self.Spb_Lat_M.setValue(abs(iMin))
        self.SpdD_Lat_S.setValue(abs(dSeg))
        
        if dDD < 0:
            self.Cb_Lat_H.setCurrentText("S")
        else:
            self.Cb_Lat_H.setCurrentText("N")
  
    def longDDtoDMS(self):
        dDD = self.SpdD_Long_GD.value()
        
        iDeg = int(dDD)
        dMin = (dDD - iDeg) * 60
        iMin = int(dMin)
        dSeg = (dMin - iMin) * 60
        
        self.Spb_Long_G.setValue(abs(iDeg))
        self.Spb_Long_M.setValue(abs(iMin))
        self.SpdD_Long_S.setValue(abs(dSeg))
        
        if dDD < 0:
            self.Cb_Long_H.setCurrentText("S")
        else:
            self.Cb_Long_H.setCurrentText("N")  
            

    def to_LatLon(self):
        """
        Esta funcion solicita al usuario los Inputs:
            Coordenada X > float
            Coordenada Y > float
            Numero de la Zona > int de 1 - 60
            Letra de la Banda > str 
            
        Calcula:
            Latitud > float. grados decimales
            Longitud > float. grados decimales

        Returns
        -------
        Una tupla de los valores de Latitud y Longitud
        (Latitud, Longitud)

        """
       
        import math

        #Variables para ambas transformaciones

        #Factor de Escala
        K0 = 0.9996

        #Excentricidades
        E = 0.00669438
        E2 = E * E
        E3 = E2 * E
        E_P2 = E / (1 - E)

        #Segundas Excentricidades
        SQRT_E = math.sqrt(1 - E)
        _E = (1 - SQRT_E) / (1 + SQRT_E)
        _E2 = _E * _E
        _E3 = _E2 * _E
        _E4 = _E3 * _E
        _E5 = _E4 * _E

        #Ecuaciones de la conversion a UTM
        M1 = (1 - E / 4 - 3 * E2 / 64 - 5 * E3 / 256)
        M2 = (3 * E / 8 + 3 * E2 / 32 + 45 * E3 / 1024)
        M3 = (15 * E2 / 256 + 45 * E3 / 1024)
        M4 = (35 * E3 / 3072)

        #Ecuaciones de la conversion a Lat Lon
        P2 = (3 / 2 * _E - 27 / 32 * _E3 + 269 / 512 * _E5)
        P3 = (21 / 16 * _E2 - 55 / 32 * _E4)
        P4 = (151 / 96 * _E3 - 417 / 128 * _E5)
        P5 = (1097 / 512 * _E4)

        #Semieje del Elipsoide (WHS84)
        R = 6378137

        #Bandas UTM
        ZONE_LETTERS = "CDEFGHJKLMNPQRSTUVWXX"

        NORTH_LETTERS = "NPQRSTUVWXX"

        SOUTH_LETTERS = "CDEFGHJKLM"


        NY = self.SpdD_UTM_Y.value()          #float(input("Ingrese la coordenada Y > "))
        northing = float(NY)
                  
        EX = self.SpdD_UTM_X.value()           #float(input("Ingrese la coordenada X > "))
        easting = float(EX)
        
        ZN = self.Spd_UTM.value()               #int(input("Ingrese el numero de la zona > "))
        zone_number = int(ZN)
        
        zone_letter = self.Cb_UTM.currentText().upper()          #input("Ingrese la letra de la Zona > ").upper()
      
        # if not 100000 <= easting <= 1000000:
            # print('ERROR:\nLa coordenada X debe estar entre 100,000 y 999,999 metros')
            # print("\nIntroduce nuevamente los valores")
            # to_LatLon()
        
        # if not 0 <= northing <= 10000000:
            # print('ERROR:\nLa coordenada Y debe estar entre 0 y 10,000,000 metros')
            # print("\nIntroduce nuevamente los valores")
            # to_LatLon()
            
        # if not 1 <= zone_number <= 60:
            # print("ERROR:\nEl numero de la zona debe estar entre 1 y 60")
            # print("\nIntroduce nuevamente los valores")
            # to_LatLon()
        
        # if zone_letter not in ZONE_LETTERS:
            # print("ERROR:\nLa letra de la Zona debe estar entre 'C' y 'X'")
            # print("Introduce nuevamente los valores")
            # to_LatLon()
            
        x = easting - 500000
        
        if zone_letter in NORTH_LETTERS:
            y = northing
            
        else:
            y = northing - 10000000
            
        m = y/K0
        
        mu = m / (R * M1)
        
        p_rad = (mu +
                 P2 * math.sin(2 * mu) +
                 P3 * math.sin(4 * mu) +
                 P4 * math.sin(6 * mu) +
                 P5 * math.sin(8 * mu))
        
        p_sin = math.sin(p_rad)
        p_sin2 = p_sin * p_sin
        
        p_cos = math.cos(p_rad)
        
        p_tan = p_sin / p_cos
        p_tan2 = p_tan**2
        p_tan4 = p_tan2**2
        
        ep_sin = 1 - E * p_sin2
        ep_sin_sqrt = math.sqrt(1 - E * p_sin2)
        
        n = R / ep_sin_sqrt
        r = (1 - E) / ep_sin
        
        c = E_P2 * p_cos**2
        c2 = c * c
        
        d = x / (n * K0)
        d2 = d * d
        d3 = d2 * d
        d4 = d3 * d
        d5 = d4 * d
        d6 = d5 * d
        
        latitude = (p_rad - (p_tan / r) *
                   (d2 / 2 -
                    d4 / 24 * (5 + 3 * p_tan2 + 10 * c - 4 * c2 - 9 * E_P2)) +
                    d6 / 720 * (61 + 90 * p_tan2 + 298 * c + 45 * p_tan4 - 252 * E_P2 - 3 * c2))
        
        cenMer = 6 * (zone_number - 1) - 177
        
        
        long = (d -
                d3 / 6 * (1 + 2 * p_tan2 + c) +
                d5 / 120 * (5 - 2 * c + 28 * p_tan2 - 3 * c2 + 8 * E_P2 + 24 * p_tan4)) / p_cos
        
        #longitud = check_angle(long + math.radians(cenMer))
        longitud =(((long + math.radians(cenMer)) + math.pi) % (2 * math.pi) - math.pi)
        
        latDegrees = math.degrees(latitude)
        lonDegrees = math.degrees(longitud)
        
        self.SpdD_Lat_GD.setValue(round(latDegrees,5)) 
        self.SpdD_Long_GD.setValue(round(lonDegrees,5))
        #self.SpdD_SpdD_UTM_Y.setValue(latDegrees) 
        #self.SpdD_SpdD_UTM_X.setValue(lonDegrees)
        
        self.Spd_UTM.setValue(zone_number)
        self.Cb_UTM.setCurrentText(zone_letter)
        self.Spb_MC.setValue(cenMer)        
        
        return (latDegrees, lonDegrees)
        
        #print(f"Latitud = {round(latDegrees,5)}")
        #print(f"Longitud = {round(lonDegrees,5)}")
        

        


    def to_UTM(self):
        """
        Esta funcion solicita al usuario los Inputs:
            Latitud > float. grados decimales
            Longitud > float. grados decimales
            
        Calcula:
            El numero de la Zona > int. huso
            El meridiano central de la zona > int. cenMer
            Banda de la zona > str. zona
            Coordenada X > float
            Coordenada Y > float

        Returns
        -------
        Una tupla de los valores de X, Y, Zona, Banda, Meridiano Central)
        (X, Y, huso, zona, cenMer)

        """

        import math

        #Variables para ambas transformaciones

        #Factor de Escala
        K0 = 0.9996

        #Excentricidades
        E = 0.00669438
        E2 = E * E
        E3 = E2 * E
        E_P2 = E / (1 - E)

        #Segundas Excentricidades
        SQRT_E = math.sqrt(1 - E)
        _E = (1 - SQRT_E) / (1 + SQRT_E)
        _E2 = _E * _E
        _E3 = _E2 * _E
        _E4 = _E3 * _E
        _E5 = _E4 * _E

        #Ecuaciones de la conversion a UTM
        M1 = (1 - E / 4 - 3 * E2 / 64 - 5 * E3 / 256)
        M2 = (3 * E / 8 + 3 * E2 / 32 + 45 * E3 / 1024)
        M3 = (15 * E2 / 256 + 45 * E3 / 1024)
        M4 = (35 * E3 / 3072)

        #Ecuaciones de la conversion a Lat Lon
        P2 = (3 / 2 * _E - 27 / 32 * _E3 + 269 / 512 * _E5)
        P3 = (21 / 16 * _E2 - 55 / 32 * _E4)
        P4 = (151 / 96 * _E3 - 417 / 128 * _E5)
        P5 = (1097 / 512 * _E4)

        #Semieje del Elipsoide (WHS84)
        R = 6378137

        #Bandas UTM
        ZONE_LETTERS = "CDEFGHJKLMNPQRSTUVWXX"

        NORTH_LETTERS = "NPQRSTUVWXX"

        SOUTH_LETTERS = "CDEFGHJKLM"



        PHI = self.SpdD_Lat_GD.value()
        phi = float(PHI)               #float(input("Ingrese la Latitud en grados decimales > "))
        
        phiRad = math.radians(phi)
        
        LAMB = self.SpdD_Long_GD.value()
        lamb =  float(LAMB)             #float(input("Ingrese la longitud en grados decimales > "))
        
        lambRad = math.radians(lamb)
        
        #Huso
        huso = int((lamb/6) + 31)
        
        self.Spd_UTM.setValue(huso)
        
        print(f"Huso = {huso}")
        
        #Meridiano central de la zona
        cenMer = 6 * (huso - 1) - 177
        print(f"Meridiano Central = {cenMer}")
        
        self.Spb_MC.setValue(cenMer)
        
        cenMer_rad = math.radians(cenMer)
        
        #Letra de Zona
        if -80 <= phi <= 84:
            zona = ZONE_LETTERS[int(phi + 80) >> 3]
            
            self.Cb_UTM.setCurrentText(zona)
            
        print(f"Zona = {zona}")
            
        cosRad= math.cos(phiRad)
        
        tanRad = math.tan(phiRad)
        
        sinRad = math.sin(phiRad)
        
        tanRad2 = tanRad**2
        
        tanRad4 = tanRad2**2
        
        #Calcula el valor de N 
        n = R / math.sqrt(1 - E * sinRad**2)
        
        c = E_P2 * cosRad**2
        
        #Ecuaciones de la proyección
        a = cosRad * (((lambRad - cenMer_rad) + math.pi) % (2 * math.pi) - math.pi)
        a2 = a * a
        a3 = a2 * a
        a4 = a3 * a
        a5 = a4 * a
        a6 = a5 * a
        
        m = R * (M1 * phiRad -
                 M2 * math.sin(2 * phiRad) +
                 M3 * math.sin(4 * phiRad) -
                 M4 * math.sin(6 * phiRad))
        
        
        X = K0 * n * (a +
                      a3 / 6 * (1 - tanRad2 + c) +
                      a5 / 120 * (5 - 18 * tanRad2 + tanRad4 + 72 * c - 58 * E_P2)) + 500000
        
        y = K0 * (m + n * tanRad * (a2 / 2 +
                  a4 / 24 * (5 - tanRad2 + 9 * c + 4 * c**2) +
                  a6 / 720 * (61 - 58 * tanRad2 + tanRad4 + 600 * c - 330 * E_P2)))

        if phi >= 0:
            Y = y
        else:
            Y = 10000000 + y
            
        print(f"X = {round(X,3)}")
        
        print(f"Y = {round(Y,3)}") 
        
        self.SpdD_UTM_Y.setValue(round(Y,3)) 
        self.SpdD_UTM_X.setValue(round(X,3))
        
        return (X, Y, huso, zona, cenMer)

        #self.SpdD_Lat_GD.value()











